<a href="https://colab.research.google.com/github/Dhawaldwivedi/Python-Basics-2/blob/main/numpy_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# numpy - statistical analysis
# pandas - data manipulation
# matplotlib - data visualization
# seaborn - data visualization

Why to use numpy ??
- faster processing
- less memory consumption
- Support for multidimensional arrays and matrices
- integration with other libraries


In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
lst = [[1,2,3],
       [4,5,6],
       [7,8,9]]

lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.ndim

2

In [8]:
arr.shape

(3, 3)

In [9]:
arr.size

9

In [10]:
# zeros and ones
z = np.zeros((3,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
o = np.ones((6,3))
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.random.random()

0.034610988134455956

In [17]:
np.random.random((2,2))

array([[0.9611918 , 0.58055106],
       [0.7148159 , 0.20076319]])

In [24]:
np.random.randint(1,6)

1

In [25]:
# arange function
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [29]:
# linspace function
np.linspace(1,11,6)

array([ 1.,  3.,  5.,  7.,  9., 11.])

In [30]:
# reshape
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.reshape(z,(5,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
z.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
a = np.array([[1,2,3,4,5],
             [4,5,6,7,8],
             [6,7,8,5,4]])

In [38]:
np.reshape(a,(5,3))

array([[1, 2, 3],
       [4, 5, 4],
       [5, 6, 7],
       [8, 6, 7],
       [8, 5, 4]])

In [39]:
np.reshape(a,(4,4))

ValueError: cannot reshape array of size 15 into shape (4,4)

In [40]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [42]:
arr-1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [44]:
arr/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [45]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [46]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
int(arr.max())

9

In [50]:
int(arr.min())

1

In [51]:
int(arr.sum())

45

In [52]:
int(arr.trace())   # sum of diagonal elements

15

In [53]:
arr1 = np.array([[2,4,5],
                 [5,3,7],
                 [8,2,3]])
arr2 = np.array([[2,1,3],
                 [4,5,9],
                 [9,1,1]])

In [54]:
arr1

array([[2, 4, 5],
       [5, 3, 7],
       [8, 2, 3]])

In [55]:
arr2

array([[2, 1, 3],
       [4, 5, 9],
       [9, 1, 1]])

In [56]:
arr3 = arr1+arr2
arr3

array([[ 4,  5,  8],
       [ 9,  8, 16],
       [17,  3,  4]])

In [58]:
int(arr3[1,2])

16

In [65]:
arr3[2,:]

array([17,  3,  4])

In [61]:
arr3[:,1]

array([5, 8, 3])

In [68]:
arr3[:,:2]

array([[ 4,  5],
       [ 9,  8],
       [17,  3]])

In [69]:
# sorting
arr3

array([[ 4,  5,  8],
       [ 9,  8, 16],
       [17,  3,  4]])

In [70]:
np.sort(arr3)

array([[ 4,  5,  8],
       [ 8,  9, 16],
       [ 3,  4, 17]])

In [71]:
arr4 = np.sort(arr3,axis=0)  # column wise
arr4

array([[ 4,  3,  4],
       [ 9,  5,  8],
       [17,  8, 16]])

In [72]:
arr5 = np.sort(arr3,axis=1)  # row wise

In [73]:
arr5

array([[ 4,  5,  8],
       [ 8,  9, 16],
       [ 3,  4, 17]])

In [74]:
# merging arrays
# vstack , hstack
arr1

array([[2, 4, 5],
       [5, 3, 7],
       [8, 2, 3]])

In [75]:
arr2

array([[2, 1, 3],
       [4, 5, 9],
       [9, 1, 1]])

In [77]:
arr5

array([[ 4,  5,  8],
       [ 8,  9, 16],
       [ 3,  4, 17]])

In [78]:
arr3 = np.vstack((arr1,arr2,arr5))
arr3

array([[ 2,  4,  5],
       [ 5,  3,  7],
       [ 8,  2,  3],
       [ 2,  1,  3],
       [ 4,  5,  9],
       [ 9,  1,  1],
       [ 4,  5,  8],
       [ 8,  9, 16],
       [ 3,  4, 17]])

In [79]:
arr4 = np.hstack((arr1,arr2))
arr4

array([[2, 4, 5, 2, 1, 3],
       [5, 3, 7, 4, 5, 9],
       [8, 2, 3, 9, 1, 1]])

In [82]:
# vsplit , hsplit
np.vsplit(arr3,3)

[array([[2, 4, 5],
        [5, 3, 7],
        [8, 2, 3]]),
 array([[2, 1, 3],
        [4, 5, 9],
        [9, 1, 1]]),
 array([[ 4,  5,  8],
        [ 8,  9, 16],
        [ 3,  4, 17]])]

In [83]:
np.hsplit(arr4,2)

[array([[2, 4, 5],
        [5, 3, 7],
        [8, 2, 3]]),
 array([[2, 1, 3],
        [4, 5, 9],
        [9, 1, 1]])]

Normalization

In [84]:
# 2,3,44,876,2,9,4-233
data = np.array([1,2,39,450,9])


In [85]:
# max , min method
max_val = np.max(data)
min_val = np.min(data)

In [86]:
normalize_array = (data-min_val)/(max_val-min_val)
normalize_array

array([0.        , 0.00222717, 0.08463252, 1.        , 0.01781737])

In [87]:
# z score normalization

# mean - average
# median - middle value for a sorted data
# mode - most frequent value

In [88]:
mean_val = np.mean(data)
std_val = np.std(data)

In [89]:
norm_array = (data-mean_val)/std_val
norm_array

array([-0.56541558, -0.55971582, -0.34882493,  1.99377388, -0.51981755])